name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: hadolint/hadolint-action@v3.1.0
      - run: docker image build --tag="${IMAGE_NAME}" ./
      - run: echo 'Hello Error' > ./index.js
      - run: docker container run --volume="$(pwd)":/app "${IMAGE_NAME}" npm run lint npm run hadolint


